<a href="https://colab.research.google.com/github/ArkSze78/Data-Science_Bootcamp/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```



### Funkcje statystyczne

In [15]:
import numpy as np
np.__version__
np.set_printoptions(precision=2)

In [3]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


sum()

In [4]:
price.sum()

np.float64(4650.1)

In [9]:
# axis=0 sumujemy po kolumnach
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [10]:
# axis=1 sumujemy po wierszach
price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

In [13]:
np.sum(price)

np.float64(4650.1)

In [14]:
np.sum(price, axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

min()

In [ ]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

max()

In [ ]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

median()

In [ ]:
np.median(price)

12.6

mean()

In [16]:
np.mean(price, axis=0)

array([  12.37,   13.07,   11.93,   12.67, 1500.  ])

std()

In [17]:
np.std(price, axis=0)

array([1.25e-01, 2.49e-01, 2.05e-01, 4.11e-01, 4.08e+02])

var()

In [18]:
np.var(price, axis=0)

array([1.56e-02, 6.22e-02, 4.22e-02, 1.69e-01, 1.67e+05])